version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: test
    volumes:
      - ./asset/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    command: "postgres"