spring:
  datasource:
    jdbc-url: jdbc:h2:mem:data_export
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  initialization-script:
    dropSchema: org/springframework/batch/core/schema-drop-h2.sql
    createSchema: org/springframework/batch/core/schema-h2.sql
